manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ClicketySplit
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: leeloo_v2
      import: app/west.yml
  self:
    path: config
